name: pideqr
description: Una aplicación para ordenar y gestionar pedidos mediante códigos QR, diseñada para optimizar el flujo de trabajo en restaurantes y cafeterías.

version: 1.0.0+1
author: Miguel Cañete <mi.canete@duocuc.cl>
homepage: https://github.com/zacion/pideqr

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.0  # <-- NUEVA DEPENDENCIA

  # Manejo de Estado
  flutter_riverpod: ^2.5.1

  # Utilidades de UI y QR
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  dynamic_color: ^1.8.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Impresión y PDF
  printing: ^5.12.0
  pdf: ^3.10.8

  # Selector de Imágenes
  image_picker: ^1.1.2     # <-- NUEVA DEPENDENCIA

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/foreground.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true
