name: pideqr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Dependencias para Firebase (Backend)
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter_riverpod: ^3.0.3

  # Para manejar QR
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  
  # Para formateo de fechas y n√∫meros
  intl: ^0.19.0 # <-- NUEVA DEPENDENCIA

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
