name: pideqr
description: Una aplicación para ordenar y gestionar pedidos mediante códigos QR, diseñada para optimizar el flujo de trabajo en restaurantes y cafeterías.

version: 1.0.0+1
homepage: https://github.com/zacion/pideqr

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  firebase_messaging: any
  cloud_functions: any
  firebase_app_check: any
  firebase_analytics: any

  # Manejo de Estado
  flutter_riverpod: any

  # Utilidades de UI y QR
  mobile_scanner: any
  qr_flutter: any
  dynamic_color: any
  intl: any
  cupertino_icons: any

  # Impresión y PDF
  printing: any
  pdf: any

  # Utilidades de Imagen
  image_picker: any
  http: any
  cached_network_image: any # <-- DEPENDENCIA AÑADIDA

  # Pagos
  webview_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test: 
    sdk: flutter

  flutter_lints: any

  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
